### ISSUE TITLE
nebula-loader and iron-icons

### ISSUE THREAD

**Issue by PPCM** [arsnebula/nebula-loader#1]
The loader is exactly what I am looking for, but I have two questions
- Is it possible to use the loader with iron-icons ?
- Is it possible to have something like PolymerElements/paper-spinner ?

Thanks for your work

**Comment by chrismbeckett** [comment]
The next generation of all my components (coming soon) will no longer use Polymer at all. Custom icons will be specified using native browser techniques such as:

```
<svg id="icon">
  <use xlink:href="#checked-icon" />
</svg>
```

My suggestion is to fork (or cut and paste) my components and customize them to fit your purpose rather than using them directly, as these will be the last version to support Bower and Polymer.

**Comment by PPCM** [comment]
Thanks for the information
